server:
  port: 8081
  servlet:
    context-path: /profile
spring:
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username : neo4j
        password : 12345678
jwt:
  secret: "186e4b79e23b663a99f7824f3c48066c517258bbaa8237d45fec6b31e0cca51b"
  app:
    jwt-access-expiration-milliseconds: 3600000
    jwt-refresh-expiration-milliseconds: 7200000